// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBT1cpN3tgmZkTdFXHZaJixfYRUzYCTztg',
    appId: '1:408918149271:web:6ba6f2c6b28e35c92001d2',
    messagingSenderId: '408918149271',
    projectId: 'mitienda-36ae8',
    authDomain: 'mitienda-36ae8.firebaseapp.com',
    storageBucket: 'mitienda-36ae8.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_Kb-YHNtFVWc8Ode09kpe5emanSzTX2Y',
    appId: '1:408918149271:android:bc6b36b165eed3512001d2',
    messagingSenderId: '408918149271',
    projectId: 'mitienda-36ae8',
    storageBucket: 'mitienda-36ae8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBEW1_HsAR010rWlPiNOvWhBB0KQkSdHNE',
    appId: '1:408918149271:ios:c575ec9030e6f3342001d2',
    messagingSenderId: '408918149271',
    projectId: 'mitienda-36ae8',
    storageBucket: 'mitienda-36ae8.appspot.com',
    iosBundleId: 'com.oscarucho2.projectstore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBEW1_HsAR010rWlPiNOvWhBB0KQkSdHNE',
    appId: '1:408918149271:ios:15e1484bc4b72b702001d2',
    messagingSenderId: '408918149271',
    projectId: 'mitienda-36ae8',
    storageBucket: 'mitienda-36ae8.appspot.com',
    iosBundleId: 'com.oscarucho2.projectstore.RunnerTests',
  );
}
